name: Deploy CloudFormation Stacks

on:
  push:
    branches: [main]
    paths:
      - 'infrastructure/**'

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # First deploy the VPC stack
      - name: Deploy VPC stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: project-one-vpc
          template: infrastructure/vpc.yml
          no-fail-on-empty-changeset: "1"
          capabilities: CAPABILITY_NAMED_IAM

      # Wait for VPC stack to complete
      - name: Wait for VPC stack to complete
        run: aws cloudformation wait stack-create-complete --stack-name project-one-vpc || aws cloudformation wait stack-update-complete --stack-name project-one-vpc

      # Then deploy the ECS stack which depends on the VPC stack
      - name: Deploy ECS stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: project-one-ecs
          template: infrastructure/ecs.yml
          parameter-overrides: "VpcStackName=project-one-vpc,BackendImage=${{ env.ECR_REGISTRY }}/project-one/backend:${{ github.sha }},FrontendImage=${{ env.ECR_REGISTRY }}/project-one/frontend:${{ github.sha }}"
          no-fail-on-empty-changeset: "1"
          capabilities: CAPABILITY_NAMED_IAM
        env:
          ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com